service: turn

plugins:
  - serverless-bundle

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  get:
    handler: turn-service/get.main
    events:
      - httpApi:
          path: /turn
          method: get
