service: turn

org: mrcportillo
app: ic-is-be-2022
frameworkVersion: '3'

plugins:
  - serverless-bundle

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: ./turn-service/get.main
    events:
      - httpApi:
          path: /turn
          method: get
